# Generated by Django 4.2.4 on 2023-10-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.CharField(default='Место для текста', max_length=2048, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.CharField(default='Место для текста', max_length=2048, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(default='Пустой заголовок', max_length=72, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(default='Пустой заголовок', max_length=72, null=True, verbose_name='Заголовок'),
        ),
    ]
